### PR TITLE
Belgemine

### LINKED ISSUE #33: Calm Lands Region State not setting correctly
**Describe the bug**
Random Encounters disabled, NPCs showing in the agency while Tidus is stood outside.
Reported by KitKat

**To Reproduce**
1. Make a save file at the Calm Lands Agency
2. Board the Airship or get a Game Over
    1. Return to Calm Lands
    2. Reload a manual or auto-save at the Agency
3. Tidus spawn at the Macalania entrance instead, but NPCs are showing inside the Agency. 
    1. Encounters are disabled

**Expected behavior**
Reloading a save should place Tidus at the room they saved in, regardless of proximity to a region entrance.
Alternatively, if placing at an entrance, then the region state needs to understand that, and not act as if Tidus is at the agency.

**Screenshots**
[Youtube Example](https://youtu.be/9-DjfGNKcjk)

Image

### LINKED ISSUE #50: Pre-Remiem Belgemine fights
Make Belgemine fights repeatable until won and remove loss reward

### PR DESCRIPTION
**Pull request by Rurusachi**
Resolves #50, and also resolves #33

### CODE REVIEW

File: src/hooks.cs [hunk 1]
```diff
@@ -500,6 +500,28 @@ private static void set(byte* code_ptr, uint[] offsets, AtelInst[] opcodes) {
         }
     }
 
+    private static void move(byte* code_ptr, uint sourceOffset, int moveBy, int size) {
+        Span<Byte> source      = new(code_ptr + sourceOffset         , size);
+        Span<Byte> destination = new(code_ptr + sourceOffset + moveBy, size);
+
+        Span<Byte> destinationSource;
+        Span<Byte> destinationDestination;
+        int destinationSize = Math.Abs(moveBy);
```
Comment (Andrewki44) [inline src/hooks.cs]: Potentially confusing variable names.
Could there be anything clearer than `destinationDestination` for example?

Comment (Andrewki44) [reply src/hooks.cs]: Fair enough lol. I approved it regardless, cause I'm not sure on a better name either tbh.
It's a nice little helper function though, to move script sections around
